### ISSUE TITLE
Changing the logging level in code outside program.cs (using Serilog)

### ISSUE THREAD

**Issue by tgriffin93** [PawelGerr/Thinktecture.Logging.Configuration#2]
Hello!  I am attempting to change the logging level via an API call, but I am having trouble accessing the instance of the SerilogConfigurationProvider that is being returned by `SerilogConfigurationSource.Build()`.  This may be due to my limited knowledge of dependency injection, but I am not sure if it is possible to inject the provider as a singleton and then reference it when creating the Serilog `LoggerConfiguration`.  If that were possible, I would think I could easily inject the configuration in any class and set the LoggingLevel from that class.  However, whenever I check the `Data` dictionary from the injected `SerilogConfigurationProvider`, it has no keys, which makes me think that it is just a completely different instance, since the logger is still logging correctly.

My Program.cs:
```
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .ConfigureLogging((hostingContext, logging) =>
            {
                var config = new ConfigurationBuilder()
                    .Add(new LoggingConfigurationSource())
                    .Build();

                var serilogConfig = new LoggerConfiguration()
                    .Enrich.FromLogContext()
                    .ReadFrom.Configuration(config)
                    .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                    .WriteTo.RollingFile(@"log\log-{Date}.txt");
                logging.AddSerilog(serilogConfig.CreateLogger(), true);

                logging.AddConsole();
            })
            .UseStartup<Startup>();
```

LoggingConfigurationSource returns a new `LoggingConfigurationProvider` on `Build()`:
```
public class LoggingConfigurationSource : IConfigurationSource
    {
        public IConfigurationProvider Build(IConfigurationBuilder builder) =>
            new LoggingConfigurationProvider();
    }
```

I am attempting to inject `LoggingConfigurationProvider` in startup:
```
public void ConfigureServices(IServiceCollection services)
        {
            ...
            services.AddSingleton<LoggingConfigurationProvider>();
        }
```

Finally, I am trying to allow getting/setting logging level from a helper class that is called by an API controller.  This is the helper class:
```
public class SettingsHelper : ISettingsHelper
    {
        private readonly LoggingConfigurationProvider _loggingConfig;
        private readonly ILogger _logger;

        public SettingsHelper(LoggingConfigurationProvider loggingConfig, ILogger<SettingsHelper> logger)
        {
            _loggingConfig = loggingConfig;
            _logger = logger;
        }

        public string GetLoggingConfig() =>
            _loggingConfig.GetLevel("Logging", "Default");

        public void SetLoggingConfig(string level)
        {
            var logLevel = Enum.GetValues(typeof(LogLevel)).Cast<LogLevel>()
                .First(l => l.ToString().Equals(level, StringComparison.OrdinalIgnoreCase));
            _loggingConfig.SetLevel(logLevel, "Logging", "Default");
        }
    }
```

I realize that I may be passing the wrong provider/category to the `LoggingConfigurationProvider`, but when it attempts to access the `Data` dictionary in `GetLevel()`, it has no keys, as I mentioned above.

I ended up finding my way here through your blog post from 2017 (https://weblogs.thinktecture.com/pawel/2017/09/net-core-in-production-changing-log-level-temporarily-2nd-approach.html), so my code is primarily based on your snippets there, but I did look through your repository and mainly found changes to allow keeping up with a collection of providers.  However, I could not find any evidence of a way to inject or reference the provider in external code.  Would you know of anything I might be able to do to make the provider injectable?

Sorry for the long post.  I would like to implement log level switching dynamically in my application and I really appreciate the work you have put into providing these instructions and examples.  I feel like I must just missing something small.  Thanks.

**Comment by PawelGerr** [comment]
Because you are using Serilog you need an other nuget package (see [Thinktecture.Logging.Configuration#with-serilog](https://github.com/PawelGerr/Thinktecture.Logging.Configuration#with-serilog)

1) Install nuget package: `Thinktecture.Extensions.Serilog.Configuration`
2) Instantiate `SerilogConfiguration` and register it with the `ConfigurationBuilder`
```
var loggingConfig = new SerilogConfiguration();

var config = new ConfigurationBuilder()
             .AddLoggingConfiguration(loggingConfig, "Serilog")
             .Build();
```
3) Register the `SerilogConfiguration` with dependency injection to be able to inject it into your classes
```
WebHost.CreateDefaultBuilder(args)
               .ConfigureServices(collection => collection.AddSingleton<ISerilogConfiguration>(loggingConfig))
```
Please pay attention that Serilog has a **Limitation**  (see **Limitation** on [Thinktecture.Logging.Configuration#with-serilog](https://github.com/PawelGerr/Thinktecture.Logging.Configuration#with-serilog))

## Example
### *.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.2</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.5" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.2.0" />
      <PackageReference Include="Serilog.Extensions.Logging" Version="2.0.4" />
      <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
      <PackageReference Include="Thinktecture.Extensions.Serilog.Configuration" Version="1.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="appsettings.json">
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
```

### appsettings.json
```
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning"
      }
    }
  }
}
```

### Program.cs
```
using System;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Serilog;
using Serilog.Events;
using Thinktecture;
using Thinktecture.Extensions.Configuration;

namespace ConsoleApp1
{
   class Program
   {
      static void Main(string[] args)
      {
         var host = CreateWebHostBuilder(args)
            .Build();

         var loggingConfig = host.Services.GetRequiredService<ISerilogConfiguration>();
         var logger = host.Services.GetRequiredService<ILogger<Program>>();

         logger.LogInformation("info");
         logger.LogWarning("warning");

         Console.WriteLine("Switching LogLevel to 'Warning'");
         loggingConfig.SetLevel(LogEventLevel.Warning);
         logger.LogInformation("info");
         logger.LogWarning("warning");
      }

      public static IWebHostBuilder CreateWebHostBuilder(string[] args)
      {
         var loggingConfig = new SerilogConfiguration();

         var config = new ConfigurationBuilder()
                      .AddJsonFile("appsettings.json")
                      .AddLoggingConfiguration(loggingConfig, "Serilog")
                      .Build();

         return WebHost.CreateDefaultBuilder(args)
                       .ConfigureServices(collection => collection.AddSingleton<ISerilogConfiguration>(loggingConfig))
                       .ConfigureLogging((hostingContext, logging) =>
                                         {
                                            logging.ClearProviders(); // ASP.NET Core adds console-logger, don't need it

                                            var serilogConfig = new LoggerConfiguration()
                                                                .Enrich.FromLogContext()
                                                                .ReadFrom.Configuration(config)
                                                                .WriteTo.Console();
                                            logging.AddSerilog(serilogConfig.CreateLogger());
                                         })
                       .UseStartup<Startup>()
            ;
      }
   }

   internal class Startup
   {
      public void Configure()
      {
      }
   }
}
```
### Console output
```
[20:20:29 INF] info
[20:20:29 WRN] warning
Switching LogLevel to 'Warning'
[20:20:29 WRN] warning
```

**Comment by tgriffin93** [comment]
Sorry for taking so long to reply.  This worked for me.  Thank you so much for your help!

I am now able to change the logging level dynamically while referencing your nuget package.  I am still having some trouble fetching the logging level, since the provider and its members are private.  However, I am currently just planning on forking the code to add a method to SerilogConfiguration to allow me to get the logging level.

I'll go ahead and close this issue since this is now working, but if you know of any any way for me to get the logging level using your nuget package, any advice would be greatly appreciated.
